version: "3.9"
services:
  discovery:
    container_name: eureka
    build: ../../../../Java projects/EurekaServer
    ports:
      - "8761:8761"
    hostname: eureka
    image: "discovery-service"


  offre_ms:
    build: ../Offre_MS
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://docker-postgres:5432/offre_ms_db
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8280:8282"
    hostname: offre
    image: "offre-service"
    depends_on:
      - discovery
      - docker-postgres

  api-gateway:
    build: ../GateWay-main
    container_name: api-gateway
    ports:
      - "8087:8087"
    expose:
      - "8087"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    depends_on:
      - discovery

  docker-postgres:
    container_name: postgres-offre
    image: "postgres:latest"
    healthcheck:
      test: ["CMD", "pg_isready","-q","-d","postgres","U","postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=offre_ms_db
    ports:
      - "5432:5432"
    restart: unless-stopped