spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true
            maxAge: 3600
  ##GATEWAY CONFIGURATIONS

server:
  port: 8087


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka